language: python
python:
  - "2.6"
  - "2.7.6"
  - "2.7.8"
  - "2.7.9"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
matrix:
  include:
    - python: '2.7_with_system_site_packages'
      env: DIST=precise-2.7.3
    - python: '2.7_with_system_site_packages'
      env: DIST=trusty-2.7.6
      dist: trusty
      sudo: required

sudo: false
addons:
  apt:
    packages:
    - liblzma-dev
install:
  - "python setup.py install"
before_script:
  - "cd test"
script:
  - "python test_lzma.py"
